/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef, useEffect} from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree} from '@react-three/fiber';
import { a } from '@react-spring/three'; //pour l'animation

import islandScene from '../assets/3d/ile_flottante_text.glb'

const Island = ({ isRotating, setIsRotating, setCurrentStage, ...props}) => {
  let isLeftKeyDown = false;
  let isRightKeyDown = false;

  const islandRef = useRef();

  const { gl, viewport } = useThree();
  //const { scene, animation } = useGLTF(islandScene);
  const { nodes, materials } = useGLTF(islandScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => { 
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    console.log("pointer down:", e.key)


    const clientX = e.touches 
      ? e.touches[0].clientX
      : e.clientX;

    lastX.current = clientX;
  }

  const handlePointerUp = (e) => { 
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }

  const handlePointerMove = (e) => { 
    e.stopPropagation();
    e.preventDefault();

    if(isRotating) {
      const clientX = e.touches 
        ? e.touches[0].clientX
        : e.clientX;

      const delta = (clientX - lastX.current) / viewport.width;

      islandRef.current.rotation.y += delta * 0.005 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.005 * Math.PI;
    }
  }

  const handleKeyDown = (e) => {
    if(e.key === 'ArrowLeft') {
      if(!isRotating) {setIsRotating(true)};
      islandRef.current.rotation.y += 0.01 * Math.PI;
      rotationSpeed.current = 0.0125;
      console.log("arrowleft:", e.key)
    } else if(e.key === 'ArrowRight') {
      if(!isRotating) setIsRotating(true);
      islandRef.current.rotation.y -= 0.01 * Math.PI;
      rotationSpeed.current = -0.0125;
      console.log("arrowright:", e.key)

    }
  }

  const handleKeyUp = (e) => {
    if(e.key === 'ArrowLeft' || e.key === 'ArrowRight'){
      setIsRotating(false);
      console.log("keyup:", e.key)
    }
    
  }

  useFrame(() => {
    if(!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if(Math.abs(rotationSpeed.current) < 0.00001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;
      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
      
    }
  });

  useEffect(() => {

    const canvas = gl.domElement;
    if ('ontouchstart' in window) {
      canvas.addEventListener('touchstart', handlePointerDown);
      canvas.addEventListener('touchend', handlePointerUp);
      canvas.addEventListener('touchmove', handlePointerMove);
    }else{
      canvas.addEventListener('pointerdown', handlePointerDown);
      canvas.addEventListener('pointerup', handlePointerUp);
      canvas.addEventListener('pointermove', handlePointerMove);
    }

    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);
    
    return () => {
      if ('ontouchstart' in window) {
        canvas.removeEventListener('touchstart', handlePointerDown);
        canvas.removeEventListener('touchend', handlePointerUp);
        canvas.removeEventListener('touchmove', handlePointerMove);
      }else{
        canvas.removeEventListener('pointerdown', handlePointerDown);
        canvas.removeEventListener('pointerup', handlePointerUp);
        canvas.removeEventListener('pointermove', handlePointerMove);
      }
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    }

  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove,handleKeyDown, handleKeyUp])


  return (

/*     <mesh ref={islandRef} {...props}>
            <primitive object={scene} />
        </mesh>
 */

      /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/



    <group ref={islandRef} {...props} dispose={null}>
      <mesh
        //castShadow
        receiveShadow
        geometry={nodes.ile.geometry}
        material={nodes.ile.material}
        position={[0, -1.37, 0]}
        scale={[1.637, 1.364, 1.637]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.podium.geometry}
        material={materials['scene.004']}
        position={[-2.577, 4.742, 0.493]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['scene.004']}
        position={[-3.274, 5.076, 0.527]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['scene.004']}
        position={[-3.164, 5.076, 1.219]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['scene.004']}
        position={[-2.891, 5.513, 0.156]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['scene.004']}
        position={[-2.73, 5.378, 1.591]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials['scene.004']}
        position={[-2.855, 5.226, 0.868]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials['scene.004']}
        position={[-2.044, 5.159, 0.815]}
        rotation={[0, -1.449, 0]}
        scale={[3.013, 3.954, 3.013]}
      />
      <group position={[-2.089, 5.322, 0.782]} rotation={[0, -1.449, 0]} scale={2.741}>
        <skinnedMesh
          geometry={nodes.Roger001.geometry}
          material={materials['queen.001']}
          skeleton={nodes.Roger001.skeleton}
        />
        <primitive object={nodes.spine} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stick.geometry}
        material={materials['queen.001']}
        position={[-2.533, 5.759, 0.492]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stick001.geometry}
        material={materials['queen.001']}
        position={[-2.391, 5.881, 1.329]}
        rotation={[0, -1.449, 0]}
        scale={2.741}
      />
      <group position={[0.187, 5.362, -3.921]} rotation={[Math.PI, -0.537, Math.PI]} scale={3.011}>
        <skinnedMesh
          geometry={nodes.Brian001.geometry}
          material={materials['queen.002']}
          skeleton={nodes.Brian001.skeleton}
        />
        <primitive object={nodes.spine_1} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar.geometry}
        material={materials['queen.002']}
        position={[0.258, 5.43, -4.101]}
        rotation={[Math.PI, -0.537, Math.PI]}
        scale={3.011}
      />
      <group position={[0.574, 5.333, 3.025]} scale={3.011}>
        <skinnedMesh
          geometry={nodes.Freddie003.geometry}
          material={materials['queen.002']}
          skeleton={nodes.Freddie003.skeleton}
        />
        <primitive object={nodes.spine_2} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.micro.geometry}
        material={materials['queen.002']}
        position={[0.568, 5.735, 3.224]}
        scale={3.011}
      />
      <group position={[3.835, 5.377, -0.406]} rotation={[0, 1.353, 0]} scale={3.011}>
        <skinnedMesh
          geometry={nodes.John001.geometry}
          material={materials['queen.002']}
          skeleton={nodes.John001.skeleton}
        />
        <primitive object={nodes.spine_3} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bass.geometry}
        material={materials['queen.002']}
        position={[4.001, 5.502, -0.379]}
        rotation={[0, 1.353, 0]}
        scale={3.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2001.geometry}
        material={nodes.arbre_2001.material}
        position={[-10.868, 4.088, -7.716]}
        rotation={[-3.123, 0.189, -3.114]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2002.geometry}
        material={nodes.arbre_2002.material}
        position={[4.85, 4.088, -10.988]}
        rotation={[-3.12, 0.579, -3.123]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2003.geometry}
        material={nodes.arbre_2003.material}
        position={[16.473, 3.277, -18.698]}
        rotation={[-3.049, -1.374, -3.02]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2004.geometry}
        material={nodes.arbre_2004.material}
        position={[10.825, 3.815, -9.689]}
        rotation={[-3.123, -0.149, -3.108]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2005.geometry}
        material={nodes.arbre_2005.material}
        position={[4.283, 4.088, -19.702]}
        rotation={[-3.109, 0.977, -3.138]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2006.geometry}
        material={nodes.arbre_2006.material}
        position={[-12.84, 3.707, -18.518]}
        rotation={[-0.036, -1.04, 0]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2007.geometry}
        material={nodes.arbre_2007.material}
        position={[-4.369, 4.088, -14.44]}
        rotation={[3.129, -0.488, 3.071]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2008.geometry}
        material={nodes.arbre_2008.material}
        position={[8.629, 3.309, -16.232]}
        rotation={[0.376, -1.271, 0.458]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2009.geometry}
        material={nodes.arbre_2009.material}
        position={[13.854, 3.476, 10.69]}
        rotation={[-0.02, -0.4, 0.023]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2010.geometry}
        material={nodes.arbre_2010.material}
        position={[-0.495, 4.204, 11.415]}
        rotation={[-0.026, -0.79, 0.013]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2012.geometry}
        material={nodes.arbre_2012.material}
        position={[-7.772, 4.088, 8.081]}
        rotation={[-0.018, -0.061, 0.03]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2013.geometry}
        material={nodes.arbre_2013.material}
        position={[-0.636, 4.088, 21.433]}
        rotation={[-0.049, -1.188, -0.014]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2014.geometry}
        material={nodes.arbre_2014.material}
        position={[13.523, 3.467, 21.666]}
        rotation={[-3.084, 1.25, 3.118]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2017.geometry}
        material={nodes.arbre_2017.material}
        position={[34.742, 3.123, -12.266]}
        rotation={[-0.018, 0.012, 0.031]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2018.geometry}
        material={nodes.arbre_2018.material}
        position={[20.737, 3.711, -7.777]}
        rotation={[-0.02, -0.378, 0.024]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2019.geometry}
        material={nodes.arbre_2019.material}
        position={[9.335, 4.088, 6.893]}
        rotation={[-1.864, 1.552, 1.895]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2020.geometry}
        material={nodes.arbre_2020.material}
        position={[13.527, 0.505, -6.675]}
        rotation={[-0.019, 0.351, 0.038]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2021.geometry}
        material={nodes.arbre_2021.material}
        position={[24.953, 4.088, 6.312]}
        rotation={[-0.025, -0.776, 0.013]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2022.geometry}
        material={nodes.arbre_2022.material}
        position={[38.02, 2.493, 0.854]}
        rotation={[-3.114, 0.839, -3.131]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2023.geometry}
        material={nodes.arbre_2023.material}
        position={[22.471, 4.088, 3.514]}
        rotation={[-0.024, 0.697, 0.046]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2024.geometry}
        material={nodes.arbre_2024.material}
        position={[16.527, 3.871, 2.909]}
        rotation={[-3.102, 1.09, 3.138]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2025.geometry}
        material={nodes.arbre_2025.material}
        position={[-23.708, 3.431, -15.654]}
        rotation={[-0.038, 1.073, 0.064]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2026.geometry}
        material={nodes.arbre_2026.material}
        position={[-24.176, 3.542, -3.386]}
        rotation={[-0.023, 0.683, 0.046]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2027.geometry}
        material={nodes.arbre_2027.material}
        position={[-21.531, 3.376, 13.729]}
        rotation={[-3.121, 0.504, -3.121]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2028.geometry}
        material={nodes.arbre_2028.material}
        position={[-28.404, 3.386, 5.616]}
        rotation={[-0.114, 1.411, 0.144]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2029.geometry}
        material={nodes.arbre_2029.material}
        position={[-14.422, 4.088, -0.19]}
        rotation={[-0.019, 0.286, 0.036]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2030.geometry}
        material={nodes.arbre_2030.material}
        position={[-12.816, 3.83, -14.259]}
        rotation={[-3.123, -0.223, -3.107]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2031.geometry}
        material={nodes.arbre_2031.material}
        position={[-19.271, 4.088, -7.423]}
        rotation={[-3.045, 1.382, 3.077]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2032.geometry}
        material={nodes.arbre_2032.material}
        position={[-21.502, 3.584, 7.968]}
        rotation={[-0.038, 1.075, 0.065]}
        scale={[0.592, 0.95, 0.592]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2033.geometry}
        material={nodes.arbre_2033.material}
        position={[14.885, 3.168, -25.086]}
        rotation={[-0.038, 1.073, 0.064]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2034.geometry}
        material={nodes.arbre_2034.material}
        position={[13.697, 3.815, -11.947]}
        rotation={[-0.023, 0.683, 0.046]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2035.geometry}
        material={nodes.arbre_2035.material}
        position={[16.343, 4.088, 5.168]}
        rotation={[-3.121, 0.504, -3.121]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2036.geometry}
        material={nodes.arbre_2036.material}
        position={[32.917, 3.295, -1.863]}
        rotation={[-0.114, 1.411, 0.144]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2037.geometry}
        material={nodes.arbre_2037.material}
        position={[25.519, 3.915, -10.281]}
        rotation={[-0.019, 0.286, 0.036]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2038.geometry}
        material={nodes.arbre_2038.material}
        position={[25.058, 3.048, -22.82]}
        rotation={[-3.123, -0.223, -3.107]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2039.geometry}
        material={nodes.arbre_2039.material}
        position={[18.603, 4.088, -15.984]}
        rotation={[-3.045, 1.382, 3.077]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2040.geometry}
        material={nodes.arbre_2040.material}
        position={[12.849, 4.088, 1.339]}
        rotation={[-3.123, 0.029, -3.111]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2041.geometry}
        material={nodes.arbre_2041.material}
        position={[9.083, 2.219, -33.038]}
        rotation={[-0.085, 0.074, 0.036]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2042.geometry}
        material={nodes.arbre_2042.material}
        position={[-1.492, 2.594, -26.813]}
        rotation={[-0.085, -0.316, 0.029]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2043.geometry}
        material={nodes.arbre_2043.material}
        position={[-14.462, 3.31, -15.358]}
        rotation={[-2.891, 1.5, 2.855]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2044.geometry}
        material={nodes.arbre_2044.material}
        position={[-11.351, 2.643, -25.504]}
        rotation={[-0.088, 0.412, 0.043]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2045.geometry}
        material={nodes.arbre_2045.material}
        position={[-2.761, 3.268, -16.901]}
        rotation={[-0.088, -0.714, 0.02]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2046.geometry}
        material={nodes.arbre_2046.material}
        position={[12.771, 2.9, -22.47]}
        rotation={[3.104, 0.777, -3.134]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2047.geometry}
        material={nodes.arbre_2047.material}
        position={[4.556, 2.748, -24.873]}
        rotation={[-0.096, 0.758, 0.054]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2048.geometry}
        material={nodes.arbre_2048.material}
        position={[-7.529, 3.042, -19.77]}
        rotation={[3.116, 1.028, 3.135]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2049.geometry}
        material={nodes.arbre_2049.material}
        position={[-24.902, 2.219, -28.781]}
        rotation={[-0.118, 0.766, 0.112]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2050.geometry}
        material={nodes.arbre_2050.material}
        position={[-29.029, 2.594, -17.224]}
        rotation={[-0.087, 0.377, 0.087]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2051.geometry}
        material={nodes.arbre_2051.material}
        position={[-31.643, 3.31, -0.119]}
        rotation={[-3.116, 0.806, 3.087]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2052.geometry}
        material={nodes.arbre_2052.material}
        position={[-35.758, 2.643, -9.901]}
        rotation={[-0.18, 1.103, 0.169]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2053.geometry}
        material={nodes.arbre_2053.material}
        position={[-20.694, 3.268, -11.272]}
        rotation={[-0.066, -0.02, 0.076]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2054.geometry}
        material={nodes.arbre_2054.material}
        position={[-14.942, 2.9, -24.207]}
        rotation={[3.115, 0.081, 3.125]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2055.geometry}
        material={nodes.arbre_2055.material}
        position={[-23.143, 2.748, -19.612]}
        rotation={[-0.546, 1.437, 0.53]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2056.geometry}
        material={nodes.arbre_2056.material}
        position={[-29.149, 3.042, -7.949]}
        rotation={[3.128, 0.332, 3.118]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2057.geometry}
        material={nodes.arbre_2057.material}
        position={[-12.838, 3.42, 26.481]}
        rotation={[-3.116, 0.798, -3.129]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2058.geometry}
        material={nodes.arbre_2058.material}
        position={[3.975, 3.658, 22.327]}
        rotation={[-3.097, -1.155, -3.07]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2059.geometry}
        material={nodes.arbre_2059.material}
        position={[-3.495, 3.026, 29.893]}
        rotation={[-3.123, 0.07, -3.112]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2060.geometry}
        material={nodes.arbre_2060.material}
        position={[-10.519, 4.088, 16.482]}
        rotation={[-3.092, 1.196, 3.126]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2061.geometry}
        material={nodes.arbre_2061.material}
        position={[-24.676, 3.318, 16.13]}
        rotation={[-0.059, -1.259, -0.025]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2062.geometry}
        material={nodes.arbre_2062.material}
        position={[-17.294, 4.088, 21.953]}
        rotation={[-3.123, -0.276, -3.106]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2063.geometry}
        material={nodes.arbre_2063.material}
        position={[20.9, 3.161, 24.854]}
        rotation={[-3.123, -0.066, -3.109]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2064.geometry}
        material={nodes.arbre_2064.material}
        position={[28.657, 3.133, 9.37]}
        rotation={[-0.042, -1.121, -0.007]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2065.geometry}
        material={nodes.arbre_2065.material}
        position={[29.561, 3.228, 19.964]}
        rotation={[-3.116, -0.794, -3.092]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2066.geometry}
        material={nodes.arbre_2066.material}
        position={[14.8, 4.088, 16.599]}
        rotation={[-3.122, 0.332, -3.117]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2067.geometry}
        material={nodes.arbre_2067.material}
        position={[5.342, 3.321, 27.137]}
        rotation={[-0.02, -0.395, 0.023]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2068.geometry}
        material={nodes.arbre_2068.material}
        position={[14.563, 3.476, 25.303]}
        rotation={[-3.098, -1.14, -3.071]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2069.geometry}
        material={nodes.arbre_2069.material}
        position={[-31.48, 3.427, 2.593]}
        rotation={[-0.047, 1.171, 0.074]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2071.geometry}
        material={nodes.arbre_2071.material}
        position={[-30.994, 3.038, 12.527]}
        rotation={[-3.086, 1.241, 3.119]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2072.geometry}
        material={nodes.arbre_2072.material}
        position={[-21.365, 4.088, 0.845]}
        rotation={[-0.025, 0.773, 0.049]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2073.geometry}
        material={nodes.arbre_2073.material}
        position={[-26.541, 3.588, -12.336]}
        rotation={[-3.118, -0.71, -3.095]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2074.geometry}
        material={nodes.arbre_2074.material}
        position={[-29.039, 4.088, -3.272]}
        rotation={[-3.113, 0.895, -3.133]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2.geometry}
        material={nodes.arbre_2.material}
        position={[3.464, 2.705, 31.487]}
        rotation={[-3.121, -0.495, -3.101]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2075.geometry}
        material={nodes.arbre_2075.material}
        position={[-15.179, 3.686, 15.709]}
        rotation={[-0.046, 1.164, 0.073]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2076.geometry}
        material={nodes.arbre_2076.material}
        position={[-0.636, 4.088, 21.433]}
        rotation={[-0.049, -1.188, -0.014]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2078.geometry}
        material={nodes.arbre_2078.material}
        position={[6.57, 4.088, 15.655]}
        rotation={[-0.019, 0.285, 0.036]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2079.geometry}
        material={nodes.arbre_2079.material}
        position={[-6.993, 3.869, 14.939]}
        rotation={[-2.882, 1.5, 2.914]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2082.geometry}
        material={nodes.arbre_2082.material}
        position={[-21.502, 3.55, 5.507]}
        rotation={[-3.123, 0.029, -3.111]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2086.geometry}
        material={nodes.arbre_2086.material}
        position={[-10.519, 4.088, 16.482]}
        rotation={[-3.092, 1.196, 3.126]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2088.geometry}
        material={nodes.arbre_2088.material}
        position={[-17.294, 4.088, 21.953]}
        rotation={[-3.123, -0.276, -3.106]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2091.geometry}
        material={nodes.arbre_2091.material}
        position={[-21.12, 3.261, 16.472]}
        rotation={[-3.123, 0.016, -3.111]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2092.geometry}
        material={nodes.arbre_2092.material}
        position={[3.464, 2.705, 31.487]}
        rotation={[-3.121, -0.495, -3.101]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2093.geometry}
        material={nodes.arbre_2093.material}
        position={[-5.116, 2.743, 25.123]}
        rotation={[-0.019, -0.317, 0.025]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2094.geometry}
        material={nodes.arbre_2094.material}
        position={[-14.674, 2.743, 41.642]}
        rotation={[-3.105, 1.054, 3.141]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2095.geometry}
        material={nodes.arbre_2095.material}
        position={[-9.9, 2.743, 32.555]}
        rotation={[-2.989, 1.451, 3.021]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2096.geometry}
        material={nodes.arbre_2096.material}
        position={[-23.507, 2.743, 28.633]}
        rotation={[-0.315, -1.512, -0.283]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2097.geometry}
        material={nodes.arbre_2097.material}
        position={[-17.839, 2.743, 36.133]}
        rotation={[-3.123, -0.021, -3.11]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2098.geometry}
        material={nodes.arbre_2098.material}
        position={[-20.154, 2.743, 29.862]}
        rotation={[-3.123, 0.272, -3.116]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2099.geometry}
        material={nodes.arbre_2099.material}
        position={[-21.564, 2.743, -24.964]}
        rotation={[-3.12, 0.588, -3.123]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2100.geometry}
        material={nodes.arbre_2100.material}
        position={[-7.931, 2.743, -38.318]}
        rotation={[-0.075, -1.325, -0.041]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2101.geometry}
        material={nodes.arbre_2101.material}
        position={[-14.964, 2.743, -30.842]}
        rotation={[-3.023, -1.417, -2.993]}
        scale={[0.908, 1.457, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2102.geometry}
        material={nodes.arbre_2102.material}
        position={[-2.905, 2.743, -23.418]}
        rotation={[-0.085, 1.355, 0.114]}
        scale={[0.568, 0.911, 0.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2103.geometry}
        material={nodes.arbre_2103.material}
        position={[-6.357, 2.743, -32.163]}
        rotation={[-0.019, -0.251, 0.026]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2104.geometry}
        material={nodes.arbre_2104.material}
        position={[-5.807, 2.743, -25.501]}
        rotation={[-0.021, -0.543, 0.02]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2105.geometry}
        material={nodes.arbre_2105.material}
        position={[11.531, 2.743, -18.572]}
        rotation={[-3.12, 0.588, -3.123]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2106.geometry}
        material={nodes.arbre_2106.material}
        position={[26.436, 2.743, -33.172]}
        rotation={[-0.075, -1.325, -0.041]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2107.geometry}
        material={nodes.arbre_2107.material}
        position={[18.734, 2.743, -24.837]}
        rotation={[-3.023, -1.417, -2.993]}
        scale={[0.993, 1.593, 0.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2108.geometry}
        material={nodes.arbre_2108.material}
        position={[31.93, 2.743, -16.882]}
        rotation={[-0.085, 1.355, 0.114]}
        scale={[0.621, 0.996, 0.621]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2109.geometry}
        material={nodes.arbre_2109.material}
        position={[28.156, 2.743, -26.443]}
        rotation={[-0.019, -0.251, 0.026]}
        scale={[1.207, 1.936, 1.207]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2110.geometry}
        material={nodes.arbre_2110.material}
        position={[28.758, 2.743, -19.16]}
        rotation={[-0.021, -0.543, 0.02]}
        scale={[0.603, 0.967, 0.603]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2111.geometry}
        material={nodes.arbre_2111.material}
        position={[9.33, 2.743, -20.15]}
        rotation={[-3.122, -0.424, -3.102]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2112.geometry}
        material={nodes.arbre_2112.material}
        position={[4.847, 2.743, -40.526]}
        rotation={[-0.019, -0.313, 0.025]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2113.geometry}
        material={nodes.arbre_2113.material}
        position={[7.704, 2.743, -29.674]}
        rotation={[-0.024, -0.711, 0.015]}
        scale={[0.993, 1.593, 0.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2114.geometry}
        material={nodes.arbre_2114.material}
        position={[21.573, 2.743, -36.553]}
        rotation={[-3.116, 0.774, -3.128]}
        scale={[0.621, 0.996, 0.621]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2115.geometry}
        material={nodes.arbre_2115.material}
        position={[11.465, 2.743, -38.419]}
        rotation={[-0.025, 0.761, 0.048]}
        scale={[1.207, 1.936, 1.207]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2116.geometry}
        material={nodes.arbre_2116.material}
        position={[17.96, 2.743, -35.07]}
        rotation={[-0.02, 0.469, 0.04]}
        scale={[0.603, 0.967, 0.603]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2117.geometry}
        material={nodes.arbre_2117.material}
        position={[-36.262, 2.743, 23.252]}
        rotation={[-3.122, -0.424, -3.102]}
        scale={[0.643, 1.032, 0.643]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2118.geometry}
        material={nodes.arbre_2118.material}
        position={[-40.01, 2.743, 6.218]}
        rotation={[-0.019, -0.313, 0.025]}
        scale={[0.643, 1.032, 0.643]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2119.geometry}
        material={nodes.arbre_2119.material}
        position={[-37.622, 2.743, 15.289]}
        rotation={[-0.024, -0.711, 0.015]}
        scale={[0.83, 1.332, 0.83]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2120.geometry}
        material={nodes.arbre_2120.material}
        position={[-26.028, 2.743, 9.539]}
        rotation={[-3.116, 0.774, -3.128]}
        scale={[0.519, 0.833, 0.519]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2121.geometry}
        material={nodes.arbre_2121.material}
        position={[-34.478, 2.743, 7.979]}
        rotation={[-0.025, 0.761, 0.048]}
        scale={[1.009, 1.618, 1.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2122.geometry}
        material={nodes.arbre_2122.material}
        position={[-29.048, 2.743, 10.779]}
        rotation={[-0.02, 0.469, 0.04]}
        scale={[0.504, 0.809, 0.504]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2123.geometry}
        material={nodes.arbre_2123.material}
        position={[-29.426, 2.743, 35.725]}
        rotation={[-3.122, -0.424, -3.102]}
        scale={[0.643, 1.032, 0.643]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2124.geometry}
        material={nodes.arbre_2124.material}
        position={[-34.853, 2.743, 18.931]}
        rotation={[-0.019, -0.313, 0.025]}
        scale={[0.643, 1.032, 0.643]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2125.geometry}
        material={nodes.arbre_2125.material}
        position={[-32.465, 2.743, 28.002]}
        rotation={[-0.024, -0.711, 0.015]}
        scale={[0.83, 1.332, 0.83]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2126.geometry}
        material={nodes.arbre_2126.material}
        position={[-20.871, 2.743, 22.252]}
        rotation={[-3.116, 0.774, -3.128]}
        scale={[0.519, 0.833, 0.519]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2127.geometry}
        material={nodes.arbre_2127.material}
        position={[-29.32, 2.743, 20.692]}
        rotation={[-0.025, 0.761, 0.048]}
        scale={[1.009, 1.618, 1.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2128.geometry}
        material={nodes.arbre_2128.material}
        position={[-23.891, 2.743, 23.492]}
        rotation={[-0.02, 0.469, 0.04]}
        scale={[0.504, 0.809, 0.504]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2129.geometry}
        material={nodes.arbre_2129.material}
        position={[14.674, 2.934, 35.152]}
        rotation={[-3.049, -1.374, -3.02]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2130.geometry}
        material={nodes.arbre_2130.material}
        position={[6.83, 2.513, 37.618]}
        rotation={[0.376, -1.271, 0.458]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2131.geometry}
        material={nodes.arbre_2131.material}
        position={[12.367, 3.266, 29.635]}
        rotation={[-0.038, 1.073, 0.064]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2132.geometry}
        material={nodes.arbre_2132.material}
        position={[11.898, 2.898, 41.903]}
        rotation={[-0.023, 0.683, 0.046]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2133.geometry}
        material={nodes.arbre_2133.material}
        position={[16.804, 3.566, 37.866]}
        rotation={[-3.045, 1.382, 3.077]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2134.geometry}
        material={nodes.arbre_2134.material}
        position={[9.732, 2.743, 35.278]}
        rotation={[-3.12, 0.588, -3.123]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2135.geometry}
        material={nodes.arbre_2135.material}
        position={[7.531, 2.743, 33.7]}
        rotation={[-3.122, -0.424, -3.102]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2136.geometry}
        material={nodes.arbre_2136.material}
        position={[-34.499, 2.472, -14.74]}
        rotation={[-3.049, -1.374, -3.02]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2137.geometry}
        material={nodes.arbre_2137.material}
        position={[-42.343, 2.562, -9.756]}
        rotation={[0.376, -1.271, 0.458]}
        scale={[0.452, 0.725, 0.452]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2138.geometry}
        material={nodes.arbre_2138.material}
        position={[-36.805, 2.343, -20.257]}
        rotation={[0.013, 1.065, 0.12]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2139.geometry}
        material={nodes.arbre_2139.material}
        position={[-37.274, 3.18, -7.989]}
        rotation={[-0.023, 0.683, 0.046]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2140.geometry}
        material={nodes.arbre_2140.material}
        position={[-32.369, 3.593, -12.026]}
        rotation={[-3.045, 1.382, 3.077]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2141.geometry}
        material={nodes.arbre_2141.material}
        position={[-39.44, 2.743, -14.614]}
        rotation={[-3.12, 0.588, -3.123]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2142.geometry}
        material={nodes.arbre_2142.material}
        position={[-41.642, 2.743, -16.192]}
        rotation={[-3.122, -0.424, -3.102]}
        scale={[0.769, 1.234, 0.769]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2143.geometry}
        material={nodes.arbre_2143.material}
        position={[43.703, 2.662, 2.338]}
        rotation={[-3.097, -1.155, -3.07]}
        scale={[0.552, 0.885, 0.552]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2144.geometry}
        material={nodes.arbre_2144.material}
        position={[36.232, 2.634, 9.904]}
        rotation={[-3.123, 0.07, -3.112]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2145.geometry}
        material={nodes.arbre_2145.material}
        position={[34.611, 2.743, 5.134]}
        rotation={[-0.019, -0.317, 0.025]}
        scale={[0.704, 1.129, 0.704]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arbre_2146.geometry}
        material={nodes.arbre_2146.material}
        position={[21.889, 4.006, 16.145]}
        rotation={[-3.123, -0.021, -3.11]}
        scale={[1.104, 1.771, 1.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spotlight.geometry}
        material={materials['scene.003']}
        position={[-2.401, -3.43, 6.103]}
        rotation={[-Math.PI, 0.379, -Math.PI]}
        scale={1.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1.geometry}
        material={materials['rock.001']}
        position={[-3.484, 3.641, 4.798]}
        rotation={[-0.099, 0.291, -0.182]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1001.geometry}
        material={materials['rock.001']}
        position={[-2.468, 3.416, 5.414]}
        rotation={[-0.271, 0.299, 0.123]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1002.geometry}
        material={materials['rock.001']}
        position={[-4.182, 3.59, 4.151]}
        rotation={[-0.144, -0.302, -0.041]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1.geometry}
        material={materials['grass.001']}
        position={[5.632, 3.925, 4.741]}
        rotation={[0, 0, -0.017]}
        scale={0.821}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1001.geometry}
        material={materials['grass.001']}
        position={[5.684, 4.028, 2.954]}
        rotation={[-0.089, 0, -0.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1002.geometry}
        material={materials['grass.001']}
        position={[6.1, 4.007, 2.167]}
        rotation={[-0.267, 0, -0.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1003.geometry}
        material={materials['grass.001']}
        position={[6.505, 3.883, 3.018]}
        rotation={[0, 0, -0.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1003.geometry}
        material={materials['rock.001']}
        position={[3.635, 3.712, 4.291]}
        rotation={[-3.004, 0.81, 2.831]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1004.geometry}
        material={materials['rock.001']}
        position={[4.341, 3.488, 3.619]}
        rotation={[-1.075, 1.276, 1.098]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1005.geometry}
        material={materials['rock.001']}
        position={[2.852, 3.661, 4.949]}
        rotation={[-0.198, 0.803, 0.145]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1004.geometry}
        material={materials['grass.001']}
        position={[3.663, 3.887, 6.082]}
        rotation={[0.081, -0.443, -0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1005.geometry}
        material={materials['grass.001']}
        position={[4.232, 3.951, 5.661]}
        rotation={[0.081, -0.443, -0.08]}
        scale={1.251}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1006.geometry}
        material={materials['grass.001']}
        position={[4.945, 4.016, 5.132]}
        rotation={[0.081, -0.443, -0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1007.geometry}
        material={materials['grass.001']}
        position={[4.95, 3.915, 6.072]}
        rotation={[0.081, -0.443, -0.08]}
        scale={0.773}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1008.geometry}
        material={materials['grass.001']}
        position={[-1.85, 3.802, 6.163]}
        rotation={[0.257, -0.638, -0.139]}
        scale={0.821}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1009.geometry}
        material={materials['grass.001']}
        position={[-3.843, 3.959, 6.342]}
        rotation={[0.9, -1.263, 0.466]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1010.geometry}
        material={materials['grass.001']}
        position={[-3.262, 4.014, 6.751]}
        rotation={[0.301, -1.088, -0.186]}
        scale={1.251}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1011.geometry}
        material={materials['grass.001']}
        position={[-2.372, 3.993, 6.748]}
        rotation={[0.301, -1.088, -0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1012.geometry}
        material={materials['grass.001']}
        position={[-2.937, 3.704, 7.447]}
        rotation={[0.301, -1.088, -0.186]}
        scale={0.773}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1013.geometry}
        material={materials['grass.001']}
        position={[5.975, 3.958, -1.025]}
        rotation={[-0.089, 0, -0.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1014.geometry}
        material={materials['grass.001']}
        position={[6.392, 3.938, -1.812]}
        rotation={[-0.267, 0, -0.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1015.geometry}
        material={materials['grass.001']}
        position={[6.797, 3.813, -0.961]}
        rotation={[0, 0, -0.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1016.geometry}
        material={materials['grass.001']}
        position={[5.65, 3.843, -2.038]}
        rotation={[0.081, -0.443, -0.08]}
        scale={0.773}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1006.geometry}
        material={materials['rock.001']}
        position={[4.999, 3.569, -2.54]}
        rotation={[-1.075, 1.276, 1.098]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1007.geometry}
        material={materials['rock.001']}
        position={[4.447, 3.588, -3.169]}
        rotation={[0.361, 0.949, -0.29]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1008.geometry}
        material={materials['rock.001']}
        position={[-5.598, 3.402, 0.155]}
        rotation={[-0.198, 0.252, -0.038]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1009.geometry}
        material={materials['rock.001']}
        position={[-5.451, 3.468, -0.867]}
        rotation={[-0.297, -1.43, -0.439]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1017.geometry}
        material={materials['grass.001']}
        position={[-6.096, 3.673, 0.827]}
        rotation={[3.114, -0.857, 3.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1018.geometry}
        material={materials['grass.001']}
        position={[-5.574, 3.656, 2.261]}
        rotation={[-2.812, -1.054, -3.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1019.geometry}
        material={materials['grass.001']}
        position={[-6.515, 3.73, 2.215]}
        rotation={[-2.812, -1.054, -3.025]}
        scale={0.773}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1010.geometry}
        material={materials['rock.001']}
        position={[0.282, 3.561, -5.743]}
        rotation={[-2.804, -1.406, -3.043]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1011.geometry}
        material={materials['rock.001']}
        position={[-0.684, 3.488, -5.633]}
        rotation={[-2.844, -0.514, -2.951]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1012.geometry}
        material={materials['rock.001']}
        position={[1.242, 3.633, -5.686]}
        rotation={[-3.004, 0.08, 3.132]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1020.geometry}
        material={materials['grass.001']}
        position={[2.287, 3.9, -5.983]}
        rotation={[-2.96, 1.054, 2.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1021.geometry}
        material={materials['grass.001']}
        position={[1.397, 3.812, -6.535]}
        rotation={[-2.631, 1.001, 2.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1022.geometry}
        material={materials['grass.001']}
        position={[-1.328, 3.613, -6.926]}
        rotation={[-2.96, 1.054, 2.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1023.geometry}
        material={materials['grass.001']}
        position={[-1.673, 3.813, -6.252]}
        rotation={[Math.PI, 1.061, 2.958]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1013.geometry}
        material={materials['rock.001']}
        position={[-4.059, 3.531, -4.066]}
        rotation={[-2.767, -0.754, -2.803]}
        scale={0.532}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1024.geometry}
        material={materials['grass.001']}
        position={[-3.644, 3.985, -4.933]}
        rotation={[-2.96, 1.054, 2.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1025.geometry}
        material={materials['grass.001']}
        position={[-4.444, 4.024, -4.605]}
        rotation={[Math.PI, 1.061, 2.958]}
        scale={0.74}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1026.geometry}
        material={materials['grass.001']}
        position={[-3.989, 3.842, -5]}
        rotation={[2.65, 0.93, -2.948]}
        scale={1.159}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_stack002.geometry}
        material={materials['scene.001']}
        position={[-0.905, 4.052, 5.965]}
        rotation={[0, -0.355, 0]}
        scale={2.187}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini002.geometry}
        material={materials['scene.002']}
        position={[3.602, 4.616, -2.881]}
        rotation={[-Math.PI, 0.783, -Math.PI]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini004.geometry}
        material={materials['scene.002']}
        position={[4.365, 4.619, 1.333]}
        rotation={[0, 1.257, 0]}
        scale={2.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini001.geometry}
        material={materials['scene.002']}
        position={[3.994, 4.616, 2.116]}
        rotation={[0, 1.069, 0]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini003.geometry}
        material={materials['scene.002']}
        position={[3.559, 4.619, 2.863]}
        rotation={[0, 0.892, 0]}
        scale={2.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini005.geometry}
        material={materials['scene.002']}
        position={[-2.572, 4.619, 3.927]}
        rotation={[0, -0.613, 0]}
        scale={2.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini006.geometry}
        material={materials['scene.002']}
        position={[-3.212, 4.616, 3.341]}
        rotation={[0, -0.801, 0]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini007.geometry}
        material={materials['scene.002']}
        position={[-3.797, 4.619, 2.705]}
        rotation={[0, -0.978, 0]}
        scale={2.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini008.geometry}
        material={materials['scene.002']}
        position={[-3.363, 4.619, -3.261]}
        rotation={[Math.PI, -0.765, Math.PI]}
        scale={2.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini009.geometry}
        material={materials['scene.002']}
        position={[-2.666, 4.616, -3.776]}
        rotation={[Math.PI, -0.576, Math.PI]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini010.geometry}
        material={materials['scene.002']}
        position={[-1.929, 4.619, -4.229]}
        rotation={[Math.PI, -0.4, Math.PI]}
        scale={2.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini011.geometry}
        material={materials['scene.002']}
        position={[1.963, 4.616, -4.013]}
        rotation={[-Math.PI, 0.389, -Math.PI]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini012.geometry}
        material={materials['scene.002']}
        position={[1.485, 4.616, 4.173]}
        rotation={[0, 0.181, 0]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amps_mini013.geometry}
        material={materials['scene.002']}
        position={[-4.69, 4.616, -0.284]}
        rotation={[Math.PI, -1.451, Math.PI]}
        scale={2.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_stack001.geometry}
        material={materials['scene.001']}
        position={[-5.001, 4.272, -2.663]}
        rotation={[Math.PI, -0.849, Math.PI]}
        scale={2.187}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_stack003.geometry}
        material={materials['scene.001']}
        position={[0.378, 5.023, -3.12]}
        rotation={[-Math.PI, 0.528, -Math.PI]}
        scale={1.642}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_stack004.geometry}
        material={materials['scene.001']}
        position={[-0.243, 5.023, -3.19]}
        rotation={[Math.PI, -0.141, Math.PI]}
        scale={1.642}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_stack005.geometry}
        material={materials['scene.001']}
        position={[2.608, 5.023, 0.643]}
        rotation={[-Math.PI, 1.121, -Math.PI]}
        scale={1.642}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_stack006.geometry}
        material={materials['scene.001']}
        position={[2.258, 5.023, -1.022]}
        rotation={[0, 1.232, 0]}
        scale={1.642}
      />
      <mesh
        visible={false}
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['rock.001']}
        position={[0.608, 3.567, 7.937]}
        rotation={[Math.PI / 2, 0, -0.204]}
      />
      <mesh
        visible={false}
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials['rock.001']}
        position={[0.683, 3.383, -8.691]}
        rotation={[Math.PI / 2, 0, 2.953]}
      />
    </group>
    
  );
}

export default Island;