/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import { useRef, useEffect, forwardRef, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';

import { DRACO_DECODER_PATH } from '../utils/draco'
import islandScene from '../assets/3d/ile_flottante_text.glb'

useGLTF.preload(islandScene, DRACO_DECODER_PATH)

const Island = forwardRef(function Island({ isRotating, setIsRotating, setCurrentStage, ...props}, ref) {
  const localRef = useRef();
  const islandRef = ref ?? localRef;

  const { gl, viewport, invalidate } = useThree();
  const { scene } = useGLTF(islandScene, DRACO_DECODER_PATH);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;
  const previousStageRef = useRef(null);

  // The ground mesh ("ile") never casts a shadow onto itself (avoids self-shadowing acne).
  // InstancedMeshes need frustumCulled = false: GLTFLoader doesn't compute an instance-aware
  // bounding sphere, so a culled batch would make all its instances vanish together.
  useLayoutEffect(() => {
    scene.traverse((o) => {
      if (o.isMesh) {
        o.receiveShadow = true;
        o.castShadow = o.name !== 'ile';
        if (o.isInstancedMesh) o.frustumCulled = false;
      }
    });
  }, [scene]);

  useFrame(() => {
    if(!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if(Math.abs(rotationSpeed.current) < 0.00001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;
      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Each stage occupies exactly 1/4 of the circle (π/2 radians = 90 degrees)
      // The circle is divided into 4 equal quadrants
      const quarterCircle = Math.PI / 2; // π/2 radians = 90 degrees

      // Determine which quarter of the circle the rotation falls into
      // Stage 3: 0 to π/2 (0° to 90°)
      // Stage 4: π/2 to π (90° to 180°)
      // Stage 1: π to 3π/2 (180° to 270°)
      // Stage 2: 3π/2 to 2π (270° to 360°)
      const quarter = Math.floor(normalizedRotation / quarterCircle);

      // Map quarter index (0-3) to stage number
      // quarter 0 → stage 3, quarter 1 → stage 4, quarter 2 → stage 1, quarter 3 → stage 2
      const stageMapping = [3, 4, 1, 2];
      const currentStageDetected = stageMapping[quarter];

      // Only update stage if it has actually changed to prevent unnecessary re-renders
      if (currentStageDetected !== previousStageRef.current) {
        previousStageRef.current = currentStageDetected;
        setCurrentStage(currentStageDetected);
      }
    }

    // Demand mode: keep scheduling frames while dragging or coasting; stops on its own once
    // the damped speed reaches exactly 0.
    if (isRotating || rotationSpeed.current !== 0) {
      invalidate();
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;

    const handlePointerDown = (e) => {
      e.stopPropagation();
      e.preventDefault();
      setIsRotating(true);

      const clientX = e.touches
        ? e.touches[0].clientX
        : e.clientX;

      lastX.current = clientX;
    }

    const handlePointerUp = (e) => {
      e.stopPropagation();
      e.preventDefault();
      setIsRotating(false);
    }

    const handlePointerMove = (e) => {
      e.stopPropagation();
      e.preventDefault();

      if(isRotating) {
        const clientX = e.touches
          ? e.touches[0].clientX
          : e.clientX;

        const delta = (clientX - lastX.current) / viewport.width;

        islandRef.current.rotation.y += delta * 0.005 * Math.PI;
        lastX.current = clientX;
        rotationSpeed.current = delta * 0.005 * Math.PI;
        invalidate();
      }
    }

    const handleKeyDown = (e) => {
      if(e.key === 'ArrowLeft') {
        if(!isRotating) {setIsRotating(true)}
        islandRef.current.rotation.y += 0.01 * Math.PI;
        rotationSpeed.current = 0.0125;
        invalidate();
      } else if(e.key === 'ArrowRight') {
        if(!isRotating) setIsRotating(true);
        islandRef.current.rotation.y -= 0.01 * Math.PI;
        rotationSpeed.current = -0.0125;
        invalidate();
      }
    }

    const handleKeyUp = (e) => {
      if(e.key === 'ArrowLeft' || e.key === 'ArrowRight'){
        setIsRotating(false);
      }
    }

    if ('ontouchstart' in window) {
      canvas.addEventListener('touchstart', handlePointerDown);
      canvas.addEventListener('touchend', handlePointerUp);
      canvas.addEventListener('touchmove', handlePointerMove);
    }else{
      canvas.addEventListener('pointerdown', handlePointerDown);
      canvas.addEventListener('pointerup', handlePointerUp);
      canvas.addEventListener('pointermove', handlePointerMove);
    }

    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    return () => {
      if ('ontouchstart' in window) {
        canvas.removeEventListener('touchstart', handlePointerDown);
        canvas.removeEventListener('touchend', handlePointerUp);
        canvas.removeEventListener('touchmove', handlePointerMove);
      }else{
        canvas.removeEventListener('pointerdown', handlePointerDown);
        canvas.removeEventListener('pointerup', handlePointerUp);
        canvas.removeEventListener('pointermove', handlePointerMove);
      }
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    }

  }, [gl, viewport.width, isRotating, setIsRotating, setCurrentStage, invalidate, islandRef])

  return (
    <group ref={islandRef} {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
});

export default Island;
